

artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_preprocessing:
  root_dir : artifacts//data_preprocessing
  original_dataset_dir : artifacts//data_ingestion//kidney-ct-scan-image
  train_data : artifacts//data_preprocessing//train
  val_data : artifacts//data_preprocessing//val








# base_model_path : artifacts/prepare_base_model/base_model.h5
# updated_base_model_path : artifacts/prepare_base_model/base_model_updated.h5