

artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_preprocessing:
  root_dir : artifacts//data_preprocessing
  original_dataset_dir : artifacts//data_ingestion//kidney-ct-scan-image
  train_data : artifacts//data_preprocessing//train
  val_data : artifacts//data_preprocessing//val


model_training:
  root_dir : artifacts//model_training
  train_data : artifacts//data_preprocessing//train
  val_data : artifacts//data_preprocessing//val
  base_model_path : artifacts//model_training//base_model.keras
  updated_base_model_path : artifacts//model_training//base_model_updated.keras


model_evaluation:
  root_dir : artifacts//model_evaluation
  path_of_model : artifacts//model_training//base_model_updated.keras
  val_data : artifacts//data_preprocessing//val
  metric_file_name : artifacts//model_evaluation//metrics.json
